class GprReaderAiPython < Formula
  # This module provides helper methods for installing Python packages into a virtual environment
  include Language::Python::Virtualenv

  # 1. METADATA
  desc "A description of your GPR Reader AI CLI tool"
  homepage "YOUR_GITHUB_PROJECT_URL_HERE" # e.g., https://github.com/YourUser/gpr-reader-ai-python
  
  # 2. SOURCE
  # Must point to the archive (.tar.gz) of a specific GitHub Release (e.g., v1.0.0)
  url "YOUR_RELEASE_ARCHIVE_URL_HERE" 
  version "1.0.0" # Must match the tag/version of the archive
  sha256 "YOUR_ARCHIVE_SHA256_HASH" # CALCULATE THIS HASH!
  license "MIT" # Replace with your actual license

  # 3. DEPENDENCIES
  # Explicitly depend on a Homebrew-managed Python version
  depends_on "python@3.12" 
  
  # Add other non-Python dependencies here if needed (e.g., depends_on "numpy")
  # depends_on "numpy" # Example if you need the Homebrew version of numpy

  # 4. PYTHON RESOURCES (CRITICAL STEP - Generated by 'poet')
  # All PyPI dependencies for your tool must be listed here as resource blocks.

  # resource "some-dependency" do
  #   url "https://files.pythonhosted.org/packages/.../some-dependency-1.2.3.tar.gz"
  #   sha256 "..."
  # end

  # resource "another-dependency" do
  #   url "https://files.pythonhosted.org/packages/.../another-dependency-4.5.6.tar.gz"
  #   sha256 "..."
  # end

  # 5. INSTALLATION LOGIC
  def install
    # This command creates an isolated Python virtual environment using the
    # brewed python@3.12, installs all the listed `resource` packages, and finally
    # installs your CLI tool (from the source tarball) into that environment, 
    # symlinking the executable script(s) into Homebrew's /opt/homebrew/bin or /usr/local/bin.
    virtualenv_install_with_resources
  end

  # 6. TEST BLOCK
  test do
    # This is a critical check to ensure the installation worked.
    # Replace "gpr-reader-ai-python" with the actual entry point name if different.
    # The --version flag is a simple, common test.
    assert_match "version #{version}", shell_output("#{bin}/gpr-reader-ai-python --version")
  end
end
